language: java


jdk:
- openjdk8


install: true

branches:
  only:
  - master

notifications:
  email: false
cache:
  directories:
  - $HOME/.m2

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent test

env:
  - CODECOV_TOKEN="56ee8f25-34f9-4f26-ad34-688cc9450163"

before_install:
  - mvn clean install;cd commons; mvn clean install;

after_success:
  - bash <(curl -s https://codecov.io/bash)
