language: java

jdk:
- oraclejdk9

install: true

branches:
  only:
  - master

notifications:
  email: false
cache:
  directories:
  - $HOME/.m2

before_install:
 - mvn clean install;cd commons; mvn clean install;
